### Test CreateUser
POST http://localhost:3000/user/create
Content-Type: application/json

{
    "email" : "dnjsxoghd@naver.com",
    "password" : "t5653121"
}

### Test JWT
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "userId" : 2,
    "email" : "dnjsxoghd@naver.com",
    "password" : "t5653121"
}


### Test JWT Validation
GET http://localhost:3000/user/resource
Cookie : jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInN1YiI6ImRuanN4b2doZEBuYXZlci5jb20iLCJpYXQiOjE3NDM1OTQxNjksImV4cCI6MTc0MzU5Nzc2OX0.522wqMqq3wV1immR4bwhxneTZS1xp6wk5nczj83tQnc
