### Test CreateUser
POST http://localhost:3000/user/create
Content-Type: application/json

{
    "email" : "dnjsxoghd@naver.com",
    "password" : "t5653121"
}

### Test JWT
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email" : "dnjsxoghd@naver.com",
    "password" : "t5653121"
}


### Test JWT Validation
GET http://localhost:3000/user/resource
Cookie : jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRuanN4b2doZEBuYXZlci5jb20iLCJhZG1pbiI6InVzZXIiLCJpYXQiOjE3NDM2NjM3MzIsImV4cCI6MTc0MzY2NzMzMn0.TFVCPr_hF9fdvBRURQK-14WHBG0RK7tzhuG77ROI3Gs
